### ISSUE TITLE
Install fails if six is not already installed

### ISSUE THREAD

**Issue by mlaferrera** [obriencj/python-javatools#104]
When installing from git master, install fails unless `six` is already installed:

``` pip install git+https://github.com/obriencj/python-javatools
Collecting git+https://github.com/obriencj/python-javatools
  Cloning https://github.com/obriencj/python-javatools to /private/var/folders/kc/nb8dszcs4b91l1z1ql4g8qb00000gn/T/pip-req-build-6i625hwn
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kc/nb8dszcs4b91l1z1ql4g8qb00000gn/T/pip-req-build-6i625hwn/setup.py", line 27, in <module>
        from javatools.cheetah.setuptools import cheetah_build_py_cmd
      File "/private/var/folders/kc/nb8dszcs4b91l1z1ql4g8qb00000gn/T/pip-req-build-6i625hwn/javatools/__init__.py", line 35, in <module>
        from six.moves import range
    ModuleNotFoundError: No module named 'six'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/kc/nb8dszcs4b91l1z1ql4g8qb00000gn/T/pip-req-build-6i625hwn/```

**Comment by obriencj** [comment]
it's not the most elegant solution, but I delayed the loading of the cheetah build_py command until build_py is actually invoked, which should give plenty of time for setup dependencies to get loaded into place.
