### ISSUE TITLE
javatools.Unimplemented: unknown constant type 19

### ISSUE THREAD

**Issue by pwntester** [obriencj/python-javatools#107]
Hi,

Got a different Unimplemented error with constant type 19 while querying a Java 9/10/11/12 modules:

```
❯ jarinfo --jar-classes --public /Users/alvaro/.sdkman/candidates/java/9.0.4-open/jmods/java.base.jmod
Traceback (most recent call last):
  File "/Users/alvaro/.pyenv/versions/3.7.0/bin/jarinfo", line 11, in <module>
    load_entry_point('javatools==1.4.0', 'console_scripts', 'jarinfo')()
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/jarinfo.py", line 330, in main
    return cli(parser.parse_args(args[1:]))
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/jarinfo.py", line 289, in cli
    cli_jarinfo(options, ji)
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/jarinfo.py", line 244, in cli_jarinfo
    cli_jar_classes(options, info)
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/jarinfo.py", line 206, in cli_jar_classes
    ci = jarinfo.get_classinfo(entry)
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/jarinfo.py", line 156, in get_classinfo
    return unpack_class(cfd)
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/__init__.py", line 2355, in unpack_class
    o.unpack(up, magic=magic)
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/__init__.py", line 451, in unpack
    self.cpool.unpack(unpacker)
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/__init__.py", line 203, in unpack
    item = _unpack_const_item(unpacker)
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/__init__.py", line 2093, in _unpack_const_item
    raise Unimplemented("unknown constant type %r" % typecode)
javatools.Unimplemented: unknown constant type 19
```

Thanks!

**Comment by pwntester** [comment]
Other modules throw `unknown constant type 20`:

```
❯ ls /Users/alvaro/.sdkman/candidates/java/9.0.4-open/jmods | xargs -I {} sh -c 'jarinfo --jar-classes --public /Users/alvaro/.sdkman/candidates/java/9.0.4-open/jmods/{} 2>&1 >/dev/null ' | grep ": unknown constant type" | sort -u
javatools.Unimplemented: unknown constant type 19
javatools.Unimplemented: unknown constant type 20
```

**Comment by obriencj** [comment]
Those are truly unimplemented, what version of java is that?

**Comment by obriencj** [comment]
Found them, looks like introduced in java 9

CONSTANT_Module and CONSTANT_Package
https://docs.oracle.com/javase/specs/jvms/se9/html/jvms-4.html#jvms-4.4

Apparently both are just references to name strings, might be able to implement that easily.

**Comment by obriencj** [comment]
I did a quick implementation of those two types and pushed to master. Would you want to give that a shot?

I don't know how the default javap would display that information, so the display of those values from classinfo may not match up. If you happen to have a javap dump of a class with those types in, I can try and emulate.

**Comment by pwntester** [comment]
Thanks! Im getting a different error now:

```
❯ jarinfo --jar-classes --public /Users/alvaro/.sdkman/candidates/java/9.0.4-open/jmods/java.base.jmod
Entry:  classes/module-info.class
Compiled from "module-info.java"
Traceback (most recent call last):
  File "/Users/alvaro/.pyenv/versions/3.7.0/bin/jarinfo", line 11, in <module>
    load_entry_point('javatools==1.4.0', 'console_scripts', 'jarinfo')()
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/jarinfo.py", line 330, in main
    return cli(parser.parse_args(args[1:]))
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/jarinfo.py", line 289, in cli
    cli_jarinfo(options, ji)
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/jarinfo.py", line 244, in cli_jarinfo
    cli_jar_classes(options, info)
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/jarinfo.py", line 208, in cli_jar_classes
    cli_print_classinfo(options, ci)
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/classinfo.py", line 229, in cli_print_classinfo
    print(info.pretty_descriptor(), end="")
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/__init__.py", line 873, in pretty_descriptor
    e = self.pretty_super()
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/__init__.py", line 851, in pretty_super
    return _pretty_class(self.get_super())
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/__init__.py", line 649, in get_super
    return self.deref_const(self.super_ref)
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/__init__.py", line 426, in deref_const
    return self.cpool.deref_const(index)
  File "/Users/alvaro/.pyenv/versions/3.7.0/lib/python3.7/site-packages/javatools-1.4.0-py3.7.egg/javatools/__init__.py", line 234, in deref_const
    raise IndexError("Requested const 0")
IndexError: Requested const 0
```

**Comment by obriencj** [comment]
Could I get a copy of that class file?

**Comment by pwntester** [comment]
BTW, you can find these files on any java9+ installation on `JAVA_HOME/jmods`

javap dump for `classes/module-info.class` is:

```
Compiled from "module-info.java"
module java.base@11.0.2 {
  exports java.io;
  exports java.lang;
  exports java.lang.annotation;
  exports java.lang.invoke;
  exports java.lang.module;
  exports java.lang.ref;
  exports java.lang.reflect;
  exports java.math;
  exports java.net;
  exports java.net.spi;
  exports java.nio;
  exports java.nio.channels;
  exports java.nio.channels.spi;
  exports java.nio.charset;
  exports java.nio.charset.spi;
  exports java.nio.file;
  exports java.nio.file.attribute;
  exports java.nio.file.spi;
  exports java.security;
  exports java.security.acl;
  exports java.security.cert;
  exports java.security.interfaces;
  exports java.security.spec;
  exports java.text;
  exports java.text.spi;
  exports java.time;
  exports java.time.chrono;
  exports java.time.format;
  exports java.time.temporal;
  exports java.time.zone;
  exports java.util;
  exports java.util.concurrent;
  exports java.util.concurrent.atomic;
  exports java.util.concurrent.locks;
  exports java.util.function;
  exports java.util.jar;
  exports java.util.regex;
  exports java.util.spi;
  exports java.util.stream;
  exports java.util.zip;
  exports javax.crypto;
  exports javax.crypto.interfaces;
  exports javax.crypto.spec;
  exports javax.net;
  exports javax.net.ssl;
  exports javax.security.auth;
  exports javax.security.auth.callback;
  exports javax.security.auth.login;
  exports javax.security.auth.spi;
  exports javax.security.auth.x500;
  exports javax.security.cert;
  exports com.sun.security.ntlm to
    java.security.sasl;
  exports jdk.internal to
    jdk.jfr;
  exports jdk.internal.jimage to
    jdk.jlink;
  exports jdk.internal.jimage.decompressor to
    jdk.jlink;
  exports jdk.internal.jmod to
    jdk.compiler,
    jdk.jlink;
  exports jdk.internal.loader to
    java.desktop,
    java.instrument,
    java.logging;
  exports jdk.internal.logger to
    java.logging;
  exports jdk.internal.misc to
    java.desktop,
    java.logging,
    java.management,
    java.naming,
    java.net.http,
    java.rmi,
    java.security.jgss,
    java.sql,
    java.xml,
    jdk.attach,
    jdk.charsets,
    jdk.compiler,
    jdk.internal.vm.ci,
    jdk.jfr,
    jdk.jlink,
    jdk.jshell,
    jdk.net,
    jdk.scripting.nashorn,
    jdk.scripting.nashorn.shell,
    jdk.unsupported;
  exports jdk.internal.module to
    java.instrument,
    java.management.rmi,
    jdk.jartool,
    jdk.jfr,
    jdk.jlink;
  exports jdk.internal.org.objectweb.asm to
    jdk.jartool,
    jdk.jfr,
    jdk.jlink,
    jdk.scripting.nashorn;
  exports jdk.internal.org.objectweb.asm.commons to
    jdk.jfr,
    jdk.scripting.nashorn;
  exports jdk.internal.org.objectweb.asm.signature to
    jdk.scripting.nashorn;
  exports jdk.internal.org.objectweb.asm.tree to
    jdk.jfr,
    jdk.jlink;
  exports jdk.internal.org.objectweb.asm.util to
    jdk.jfr,
    jdk.scripting.nashorn;
  exports jdk.internal.org.xml.sax to
    jdk.jfr;
  exports jdk.internal.org.xml.sax.helpers to
    jdk.jfr;
  exports jdk.internal.perf to
    java.management,
    jdk.internal.jvmstat,
    jdk.management.agent;
  exports jdk.internal.ref to
    java.desktop,
    jdk.unsupported;
  exports jdk.internal.reflect to
    java.logging,
    java.sql,
    java.sql.rowset,
    jdk.dynalink,
    jdk.scripting.nashorn,
    jdk.unsupported;
  exports jdk.internal.util.jar to
    jdk.jartool;
  exports jdk.internal.util.xml to
    jdk.jfr;
  exports jdk.internal.util.xml.impl to
    jdk.jfr;
  exports jdk.internal.vm to
    jdk.internal.jvmstat,
    jdk.management.agent;
  exports jdk.internal.vm.annotation to
    jdk.internal.vm.ci,
    jdk.unsupported;
  exports sun.net to
    java.net.http,
    jdk.naming.dns;
  exports sun.net.dns to
    java.security.jgss,
    jdk.naming.dns;
  exports sun.net.ext to
    jdk.net;
  exports sun.net.util to
    java.desktop,
    java.net.http,
    jdk.jconsole;
  exports sun.net.www to
    java.desktop,
    java.net.http,
    jdk.jartool;
  exports sun.net.www.protocol.http to
    java.security.jgss;
  exports sun.nio.ch to
    java.management,
    jdk.crypto.cryptoki,
    jdk.net,
    jdk.sctp,
    jdk.unsupported;
  exports sun.nio.cs to
    java.desktop,
    jdk.charsets;
  exports sun.nio.fs to
    jdk.unsupported;
  exports sun.reflect.annotation to
    jdk.compiler;
  exports sun.reflect.generics.reflectiveObjects to
    java.desktop;
  exports sun.reflect.misc to
    java.datatransfer,
    java.desktop,
    java.management,
    java.management.rmi,
    java.rmi,
    java.sql.rowset;
  exports sun.security.action to
    java.desktop,
    java.security.jgss;
  exports sun.security.internal.interfaces to
    jdk.crypto.cryptoki;
  exports sun.security.internal.spec to
    jdk.crypto.cryptoki;
  exports sun.security.jca to
    java.smartcardio,
    jdk.crypto.cryptoki,
    jdk.crypto.ec,
    jdk.naming.dns;
  exports sun.security.pkcs to
    jdk.crypto.ec,
    jdk.jartool;
  exports sun.security.provider to
    java.rmi,
    java.security.jgss,
    jdk.crypto.cryptoki,
    jdk.security.auth;
  exports sun.security.provider.certpath to
    java.naming;
  exports sun.security.rsa to
    jdk.crypto.cryptoki;
  exports sun.security.ssl to
    java.security.jgss;
  exports sun.security.timestamp to
    jdk.jartool;
  exports sun.security.tools to
    jdk.jartool;
  exports sun.security.util to
    java.desktop,
    java.naming,
    java.rmi,
    java.security.jgss,
    java.security.sasl,
    java.smartcardio,
    java.xml.crypto,
    jdk.crypto.cryptoki,
    jdk.crypto.ec,
    jdk.jartool,
    jdk.security.auth,
    jdk.security.jgss;
  exports sun.security.util.math to
    jdk.crypto.ec;
  exports sun.security.util.math.intpoly to
    jdk.crypto.ec;
  exports sun.security.validator to
    jdk.jartool;
  exports sun.security.x509 to
    jdk.crypto.cryptoki,
    jdk.crypto.ec,
    jdk.jartool;
  exports sun.util.cldr to
    jdk.jlink;
  exports sun.util.locale.provider to
    java.desktop,
    jdk.jlink,
    jdk.localedata;
  exports sun.util.logging to
    java.desktop,
    java.logging,
    java.prefs;
  exports sun.util.resources to
    jdk.localedata;
  uses java.lang.System$LoggerFinder;
  uses java.net.ContentHandlerFactory;
  uses java.net.spi.URLStreamHandlerProvider;
  uses java.nio.channels.spi.AsynchronousChannelProvider;
  uses java.nio.channels.spi.SelectorProvider;
  uses java.nio.charset.spi.CharsetProvider;
  uses java.nio.file.spi.FileSystemProvider;
  uses java.nio.file.spi.FileTypeDetector;
  uses java.security.Provider;
  uses java.text.spi.BreakIteratorProvider;
  uses java.text.spi.CollatorProvider;
  uses java.text.spi.DateFormatProvider;
  uses java.text.spi.DateFormatSymbolsProvider;
  uses java.text.spi.DecimalFormatSymbolsProvider;
  uses java.text.spi.NumberFormatProvider;
  uses java.time.chrono.AbstractChronology;
  uses java.time.chrono.Chronology;
  uses java.time.zone.ZoneRulesProvider;
  uses java.util.spi.CalendarDataProvider;
  uses java.util.spi.CalendarNameProvider;
  uses java.util.spi.CurrencyNameProvider;
  uses java.util.spi.LocaleNameProvider;
  uses java.util.spi.ResourceBundleControlProvider;
  uses java.util.spi.ResourceBundleProvider;
  uses java.util.spi.TimeZoneNameProvider;
  uses java.util.spi.ToolProvider;
  uses javax.security.auth.spi.LoginModule;
  uses jdk.internal.logger.DefaultLoggerFinder;
  uses sun.text.spi.JavaTimeDateTimePatternProvider;
  uses sun.util.locale.provider.LocaleDataMetaInfo;
  uses sun.util.resources.LocaleData$CommonResourceBundleProvider;
  uses sun.util.resources.LocaleData$SupplementaryResourceBundleProvider;
  uses sun.util.spi.CalendarProvider;
  provides  java.nio.file.spi.FileSystemProvider with
    jdk.internal.jrtfs.JrtFileSystemProvider;
}
```

(You need to use java 9 javap version)

**Comment by pwntester** [comment]
Sure, here you have:
[module-info.class.zip](https://github.com/obriencj/python-javatools/files/3326221/module-info.class.zip)

**Comment by obriencj** [comment]
I can at least make it not crash, but I can't offer full java 9 support within any kind of reasonable timeframe. I'd need to dig up a lot to figure out this plus other changes.

**Comment by pwntester** [comment]
That would work for me :)

**Comment by obriencj** [comment]
Can you verify no crashing from master? I created issue #108 with a milestone of Javatools 1.5.0 to try and get JDK 9 features implemented cleanly.

If we're at least not crashing for you, I'll consider this "good enough" (bleh) for 1.4.0 which technically is just at level of JDK 8
