### ISSUE TITLE
Error running jarinfo with --jar-requires

### ISSUE THREAD

**Issue by TACIXAT** [obriencj/python-javatools#109]
```
Traceback (most recent call last):
  File "/home/me/.local/bin/jarinfo", line 10, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.6/site-packages/javatools/jarinfo.py", line 330, in main
    return cli(parser.parse_args(args[1:]))
  File "/home/me/.local/lib/python3.6/site-packages/javatools/jarinfo.py", line 289, in cli
    cli_jarinfo(options, ji)
  File "/home/me/.local/lib/python3.6/site-packages/javatools/jarinfo.py", line 241, in cli_jarinfo
    cli_jar_requires(options, info)
  File "/home/me/.local/lib/python3.6/site-packages/javatools/jarinfo.py", line 224, in cli_jar_requires
    for required in sorted(jarinfo.get_requires().keys()):
  File "/home/me/.local/lib/python3.6/site-packages/javatools/jarinfo.py", line 120, in get_requires
    self._collect_requires_provides()
  File "/home/me/.local/lib/python3.6/site-packages/javatools/jarinfo.py", line 105, in _collect_requires_provides
    for sym in ci.get_requires():
  File "/home/me/.local/lib/python3.6/site-packages/javatools/__init__.py", line 963, in get_requires
    self._requires = set(self._get_requires())
  File "/home/me/.local/lib/python3.6/site-packages/javatools/__init__.py", line 929, in _get_requires
    if t[1] == "L":
IndexError: tuple index out of range
```

**Comment by obriencj** [comment]
Could you please verify whether the master branch fixes your issues, @TACIXAT ?

**Comment by TACIXAT** [comment]
I'm sorry, I have literally no idea what I was doing with this library at this point lmao.

**Comment by obriencj** [comment]
haha, no worries. Honestly I'm in the same boat. I wrote it for something specific many years ago, then stopped doing that thing also years ago, and have just been letting people make suggestions or complaints since then. Have fun out there :)
