### ISSUE TITLE
Error in _unpack_wide() in Python3

### ISSUE THREAD

**Issue by jgrunzweig** [obriencj/python-javatools#115]
Hello,

Noticed an issue present in _unpack_wide() when using javatools in Python 3.7. Information below. The issue appears to be the result of Python3 returning an ordinal already when specifying a single offset in a sequence of bytes. 

For example:

**Python2**

```
>>> data = "a string of importance"
>>> data[0]
'a'
```

**Python3**

```
>>> data = b"some bytes of importance"
>>> data[0]
115
```

The easiest fix is to probably just specify a range, adding 1 to the offset:

**Python2**

```
>>> data = "a string of importance"
>>> data[0:1]
'a'
>>> len(data)
22
>>> data[21:22]
'e'
```

**Python3**

```
>>> data = b"some bytes of importance"
>>> data[0:1]
b's'
>>> len(data)
24
>>> data[23:24]
b'e'
```

### Replication of Issue

```
jgrunzweig$ python3 -m pip install javatools --upgrade
Requirement already up-to-date: javatools in /usr/local/lib/python3.7/site-packages (1.5.0)
Requirement already satisfied, skipping upgrade: Cheetah3 in /usr/local/lib/python3.7/site-packages (from javatools) (3.2.4)
Requirement already satisfied, skipping upgrade: M2Crypto>=0.26.0 in /usr/local/lib/python3.7/site-packages (from javatools) (0.35.2)
Requirement already satisfied, skipping upgrade: six in /usr/local/Cellar/protobuf/3.11.4/libexec/lib/python3.7/site-packages (from javatools) (1.14.0)

$ python3
Python 3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from javatools import opcodes
>>> code = b'\xb2\x00>6\x07\xb8\x00\x0fL\xbb\x00\x15Y+\xb7\x00\x17M,\xb6\x00\x1a\x99\x00F,\xb6\x00\x1e\x88>\xbb\x00"Y,\xb7\x00$:\x04\x11\x04\x00\xbc\x08:\x05\x036\x06\xbb\x00\'Y\xb7\x00)\x19\x05\xb6\x00*\x19\x04\x19\x05\xb6\x00.\xc4\x84\x00\x06\x04\x00\x15\x06\x1d\xa1\xff\xe4\x19\x04\x15\x07\x9a\xff\xeb\xb6\x001\xb1'
>>> for line in opcodes.disassemble(code): print(line)
... 
(0, 178, (62,))
(3, 54, (7,))
(5, 184, (15,))
(8, 76, ())
(9, 187, (21,))
(12, 89, ())
(13, 43, ())
(14, 183, (23,))
(17, 77, ())
(18, 44, ())
(19, 182, (26,))
(22, 153, (70,))
(25, 44, ())
(26, 182, (30,))
(29, 136, ())
(30, 62, ())
(31, 187, (34,))
(34, 89, ())
(35, 44, ())
(36, 183, (36,))
(39, 58, (4,))
(41, 17, (1024,))
(44, 188, (8,))
(46, 58, (5,))
(48, 3, ())
(49, 54, (6,))
(51, 187, (39,))
(54, 89, ())
(55, 183, (41,))
(58, 25, (5,))
(60, 182, (42,))
(63, 25, (4,))
(65, 25, (5,))
(67, 182, (46,))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/javatools/opcodes.py", line 253, in disassemble
    args, offset = fmt(bytecode, offset)
  File "/usr/local/lib/python3.7/site-packages/javatools/opcodes.py", line 214, in _unpack_wide
    code = ord(bc[offset])
TypeError: ord() expected string of length 1, but int found
```

Proposed fix:

```
code = ord(bc[offset:offset+1])
```

**Comment by obriencj** [comment]
I think the proposal makes sense, could you submit a PR?

**Comment by jgrunzweig** [comment]
Happy to. Created https://github.com/obriencj/python-javatools/pull/116. Didn't seem right to add myself as an AUTHOR for such a minor change :).

**Comment by jgrunzweig** [comment]
Fix looks to work as expected. Closing the ticket.
